version: '3.8'

services:
  ollama-proxy:
    build: .
    ports:
      - "11434:11434"
    env_file:
      - .env
    environment:
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - FREE_MODE=${FREE_MODE:-true}
    volumes:
      - ./models-filter:/models-filter:ro
      - proxy-data:/data
    working_dir: /data
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "wget", "--quiet", "--tries=1", "--spider", "http://localhost:11434/"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

volumes:
  proxy-data:
